repos:
-   repo: https://github.com/psf/black
    rev: 21.11b0
    hooks:
    - id: black
      args: [--line-length=79]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8

