steps:
  - name: gcr.io/cloud-builders/git
    args: ['fetch', '--unshallow']

  - name: "gcr.io/world-fishing-827/github.com/globalfishingwatch/pypi-tools:3.6"
    id: "BUILD WHEEL"
    entrypoint: "python"
    args: ["setup.py", "sdist", "bdist_wheel", "--universal"]
    waitFor: ["-"]

  - name: "gcr.io/world-fishing-827/github.com/globalfishingwatch/pypi-tools:3.6"
    id: "push to pypi"
    entrypoint: "twine"
    args:
      [
        "upload",
        "/workspace/dist/*",
        "-u", "$_PYPI_USERNAME",
        "-p", "$$PYPI_PASSWORD",
      ]
    waitFor: ["BUILD WHEEL"]
    secretEnv: [ 'PYPI_PASSWORD' ]

availableSecrets:
  secretManager:
  - versionName: $_PYPI_PASSWORD
    env: 'PYPI_PASSWORD'

timeout: 900s
