steps:
  - name: gcr.io/cloud-builders/git
    args:
      - fetch
      - '--unshallow'
  - name: 'gcr.io/world-fishing-827/github.com/globalfishingwatch/pypi-tools:3.6'
    args:
      - setup.py
      - sdist
      - bdist_wheel
      - '--universal'
    id: BUILD WHEEL
    waitFor:
      - '-'
    entrypoint: python
  - name: 'gcr.io/world-fishing-827/github.com/globalfishingwatch/pypi-tools:3.6'
    args:
      - '-c'
      - |
        twine upload /workspace/dist/* -u $_PYPI_USERNAME -p $$PASSWORD --verbose
    id: push to pypi
    waitFor:
      - BUILD WHEEL
    entrypoint: bash
    secretEnv:
      - PASSWORD
timeout: 900s
availableSecrets:
  secretManager:
    - versionName: $_PYPI_PASSWORD
      env: PASSWORD
